#!/bin/sh
# Author : Virink <virink@outlook.com>
# Date   : 2019/12/16, 17:12

mysql_ready() {
    mysqladmin ping -h 127.0.0.1 -uping -pping > /dev/null 2>&1
}

while !(mysql_ready)
do
    mysql_ready
    if [ $? -ne 0 ]; then
        mysqld_safe &
    fi
    sleep 3s
done

if [[ -f /var/www/html/db.sql ]]; then
    mysql -h 127.0.0.1 -uroot -proot -e "source /var/www/html/db.sql"
    rm -f /var/www/html/db.sql
fi

if [[ -f /flag.sh ]]; then
    source /flag.sh
fi

while true
do
    mysql_ready
    if [ $? -ne 0 ]; then
        mysqld_safe &
    fi
    ps -e | grep 'php-fpm' > /dev/null
    if [ $? -ne 0 ]; then
        php-fpm &
    fi
    ps -e | grep 'nginx:' > /dev/null
    if [ $? -ne 0 ]; then
        nginx &
    fi
    sleep 5s
done
